// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.igeekinc.util.discburning.remote;

public final class RemoteDiscBurningEventDeliveryImpl_Stub
    extends java.rmi.server.RemoteStub
    implements com.igeekinc.util.discburning.remote.RemoteDiscBurningEventDelivery, java.rmi.Remote
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("void burnDeviceEvent(com.igeekinc.util.discburning.BurnDeviceEvent)")
    };
    
    private static final long interfaceHash = -7768647444684826844L;
    
    // constructors
    public RemoteDiscBurningEventDeliveryImpl_Stub() {
	super();
    }
    public RemoteDiscBurningEventDeliveryImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of burnDeviceEvent(BurnDeviceEvent)
    public void burnDeviceEvent(com.igeekinc.util.discburning.BurnDeviceEvent $param_BurnDeviceEvent_1)
	throws java.rmi.RemoteException
    {
	try {
	    java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 0, interfaceHash);
	    try {
		java.io.ObjectOutput out = call.getOutputStream();
		out.writeObject($param_BurnDeviceEvent_1);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling arguments", e);
	    }
	    ref.invoke(call);
	    ref.done(call);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
