// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.igeekinc.util.discburning.remote;

public final class RemoteDiscBurningEventDeliveryImpl_Skel
    implements java.rmi.server.Skeleton
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("void burnDeviceEvent(com.igeekinc.util.discburning.BurnDeviceEvent)")
    };
    
    private static final long interfaceHash = -7768647444684826844L;
    
    public java.rmi.server.Operation[] getOperations() {
	return (java.rmi.server.Operation[]) operations.clone();
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash)
	throws java.lang.Exception
    {
	if (hash != interfaceHash)
	    throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
	
	com.igeekinc.util.discburning.remote.RemoteDiscBurningEventDeliveryImpl server = (com.igeekinc.util.discburning.remote.RemoteDiscBurningEventDeliveryImpl) obj;
	switch (opnum) {
	case 0: // burnDeviceEvent(BurnDeviceEvent)
	{
	    com.igeekinc.util.discburning.BurnDeviceEvent $param_BurnDeviceEvent_1;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_BurnDeviceEvent_1 = (com.igeekinc.util.discburning.BurnDeviceEvent) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    server.burnDeviceEvent($param_BurnDeviceEvent_1);
	    try {
		call.getResultStream(true);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	default:
	    throw new java.rmi.UnmarshalException("invalid method number");
	}
    }
}
