// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.igeekinc.indelible.oid;

public final class RemoteOIDSupplierImpl_Skel
    implements java.rmi.server.Skeleton
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("com.igeekinc.indelible.oid.GeneratorID getGeneratorID()"),
	new java.rmi.server.Operation("com.igeekinc.indelible.oid.ObjectID setTimeAndUniquifier(com.igeekinc.indelible.oid.ObjectID)")
    };
    
    private static final long interfaceHash = -8290246169820277968L;
    
    public java.rmi.server.Operation[] getOperations() {
	return (java.rmi.server.Operation[]) operations.clone();
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash)
	throws java.lang.Exception
    {
	if (hash != interfaceHash)
	    throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
	
	com.igeekinc.indelible.oid.RemoteOIDSupplierImpl server = (com.igeekinc.indelible.oid.RemoteOIDSupplierImpl) obj;
	switch (opnum) {
	case 0: // getGeneratorID()
	{
	    call.releaseInputStream();
	    com.igeekinc.indelible.oid.GeneratorID $result = server.getGeneratorID();
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 1: // setTimeAndUniquifier(ObjectID)
	{
	    com.igeekinc.indelible.oid.ObjectID $param_ObjectID_1;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_ObjectID_1 = (com.igeekinc.indelible.oid.ObjectID) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    com.igeekinc.indelible.oid.ObjectID $result = server.setTimeAndUniquifier($param_ObjectID_1);
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	default:
	    throw new java.rmi.UnmarshalException("invalid method number");
	}
    }
}
